[workspace]
members = ["pdsmigration-common",
    "pdsmigration-gui",
    "pdsmigration-web"]
resolver = "2"

[workspace.package]
version = "0.22.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/NorthskySocial/pds-migration-backend"

[workspace.dependencies]
pdsmigration-common = { path = "pdsmigration-common", version = "0.22.0" }

tokio = "1.53.1"
reqwest = { version = "0.13.5", default-features = false, features = ["default-tls"] }
bsky-sdk = { version = "0.1.24", default-features = false, features = ["default-client"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
derive_more = "2.1.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
futures-util = "0.3.34"
ipld-core = "0.4.3"

wiremock = "0.6.5"

[profile.dev]
debug = 2

[profile.test]
debug = 1

[profile.release]
debug = 0

[profile.release-docker]
inherits = "release"
strip = "symbols"
lto = "thin"
codegen-units = 1
opt-level = 3
