[package]
name = "pdsmigration-gui"
version.workspace = true
edition.workspace = true
include = [
    "**/*.rs",
    "Cargo.toml",
]
license.workspace = true
repository.workspace = true
description = "Desktop application to migrate an AT Protocol account between PDS servers"

[lib]
doctest = false

[dependencies]
pdsmigration-common = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
bsky-sdk = { workspace = true }
egui = { version = "0.32" }
eframe = { version = "0.32", features = ["glow", "wgpu"] }
atrium-xrpc = "0.12.4"
zip = { version = "8.6.0", default-features = false, features = ["aes-crypto"] }
secp256k1 = { version = "0.33.1", features = ["global-context"] }
multibase = "0.9.3"
unsigned-varint = "0.8.0"
rand = { version = "0.10.3", features = ["thread_rng"] }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
egui_extras = { version = "0.32", default-features = false, features = ["image"] }
serde = { workspace = true }
serde_json = { workspace = true }
base64ct = { version = "1.8.3", features = ["alloc"] }
sha2 = "0.11.0"
serde_ipld_dagcbor = "0.7.0"
indexmap = { version = "2.14.2", features = ["serde"] }
cid = "0.11.3"
hex = "0.4.3"
ipld-core = { workspace = true }
rfd = "0.17"
reqwest = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros"] }

# fallback to x11 on linux if wayland support is not available
[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30", features = ["x11"] }

# embeds the icon and the version information into the .exe
[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.31"

[package.metadata.deb]
maintainer = "Northsky Social <support@northskysocial.com>"
license-file = ["../LICENSE", "0"]
section = "utils"
priority = "optional"
depends = "$auto"
assets = [
    ["target/release/pdsmigration-gui", "usr/bin/", "755"],
    ["assets/pdsmigration-gui.desktop", "usr/share/applications/", "644"],
    ["assets/Northsky-Icon_Color.png", "usr/share/pixmaps/pdsmigration-gui.png", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/pdsmigration-gui", dest = "/usr/bin/pdsmigration-gui", mode = "755" },
    { source = "assets/pdsmigration-gui.desktop", dest = "/usr/share/applications/pdsmigration-gui.desktop", mode = "644" },
    { source = "assets/Northsky-Icon_Color.png", dest = "/usr/share/pixmaps/pdsmigration-gui.png", mode = "644" },
]
